In [7]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input, decode_predictions
import os

# Define the path to your trained model and the directory of images you want to classify
model_path = 'VGG16_image_classifier.h5'
image_dir = 'Test'

# Load the trained model
model = tf.keras.models.load_model(model_path)
model.class_names = ['blue', 'green', 'orange', 'white']  # Define the class names

# Define image dimensions (must match the dimensions used during training)
img_height = 128
img_width = 128


def load_and_preprocess_image(img_path):
    """
    Load and preprocess a single image for the model.
    """
    img = image.load_img(img_path, target_size=(img_height, img_width))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension
    img_array = preprocess_input(img_array)  # Preprocess for MobileNetV2
    return img_array

def predict_image(img_path):
    """
    Predict the class of a single image using the trained model.
    """
    img_array = load_and_preprocess_image(img_path)
    predictions = model.predict(img_array)
    print(predictions)
    predicted_index = np.argmax(predictions[0])
    predicted_class = model.class_names[predicted_index]
    return predicted_class

def classify_images(image_dir):
    """
    Classify all images in the given directory.
    """
    # List all image files in the directory
    image_files = [f for f in os.listdir(image_dir) if os.path.isfile(os.path.join(image_dir, f))]
    
    for img_file in image_files:
        img_path = os.path.join(image_dir, img_file)
        predicted_class = predict_image(img_path)
        print(f"Image: {img_file} - Predicted Class: {predicted_class}")

# Run the classification
classify_images(image_dir)

1/1 [==============================] - 1s 571ms/step
[[9.9976569e-01 3.8664766e-06 1.9499095e-04 3.5505040e-05]]
Image: blue.jpeg - Predicted Class: blue
1/1 [==============================] - 0s 233ms/step
[[0.2896742  0.22858128 0.27887607 0.20286848]]
Image: green.jpeg - Predicted Class: blue
1/1 [==============================] - 0s 210ms/step
[[0.01425731 0.7074315  0.2730579  0.00525335]]
Image: green1.jpeg - Predicted Class: green
1/1 [==============================] - 0s 213ms/step
[[2.2274494e-01 7.7691805e-01 3.2882960e-04 8.1388898e-06]]
Image: green2.jpeg - Predicted Class: green
1/1 [==============================] - 0s 231ms/step
[[4.3946557e-08 9.9997032e-01 2.9653480e-05 9.9091313e-10]]
Image: green3.jpeg - Predicted Class: green
1/1 [==============================] - 0s 231ms/step
[[1.000000e+00 7.161232e-21 2.151472e-21 6.513374e-26]]
Image: orang3.jpeg - Predicted Class: blue
1/1 [==============================] - 0s 231ms/step
[[7.0793368e-04 3.6004241e-10 9.9929202