In [2]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input, decode_predictions
import os

# Define the path to your trained model and the directory of images you want to classify
model_path = 'VGG16_image_classifier.h5'
image_dir = 'Test'

# Load the trained model
model = tf.keras.models.load_model(model_path)
model.class_names = ['blue', 'green', 'orange', 'white']  # Define the class names

# Define image dimensions (must match the dimensions used during training)
img_height = 224
img_width = 224


def load_and_preprocess_image(img_path):
    """
    Load and preprocess a single image for the model.
    """
    img = image.load_img(img_path, target_size=(img_height, img_width))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension
    img_array = preprocess_input(img_array)  # Preprocess for MobileNetV2
    return img_array

def predict_image(img_path):
    """
    Predict the class of a single image using the trained model.
    """
    img_array = load_and_preprocess_image(img_path)
    predictions = model.predict(img_array)
    print(predictions)
    predicted_index = np.argmax(predictions[0])
    predicted_class = model.class_names[predicted_index]
    return predicted_class

def classify_images(image_dir):
    """
    Classify all images in the given directory.
    """
    # List all image files in the directory
    image_files = [f for f in os.listdir(image_dir) if os.path.isfile(os.path.join(image_dir, f))]
    
    for img_file in image_files:
        img_path = os.path.join(image_dir, img_file)
        predicted_class = predict_image(img_path)
        print(f"Image: {img_file} - Predicted Class: {predicted_class}")

# Run the classification
classify_images(image_dir)

1/1 [==============================] - 1s 615ms/step
[[9.9939024e-01 6.0969120e-04 1.7026352e-08 7.0435968e-10]]
Image: blue.jpeg - Predicted Class: blue
1/1 [==============================] - 0s 400ms/step
[[1.3267200e-03 9.9808133e-01 1.8602368e-04 4.0600725e-04]]
Image: green.jpeg - Predicted Class: green
1/1 [==============================] - 0s 384ms/step
[[3.0704381e-08 1.0000000e+00 3.9378891e-09 2.1571708e-10]]
Image: green1.jpeg - Predicted Class: green
1/1 [==============================] - 0s 389ms/step
[[2.5397795e-04 9.9970824e-01 3.7616657e-05 1.2009552e-07]]
Image: green2.jpeg - Predicted Class: green
1/1 [==============================] - 0s 392ms/step
[[8.1593898e-04 9.9814129e-01 8.3260296e-04 2.1008561e-04]]
Image: green3.jpeg - Predicted Class: green
1/1 [==============================] - 0s 396ms/step
[[9.9997008e-01 1.6606572e-09 2.9975419e-05 4.9350998e-08]]
Image: orang3.jpeg - Predicted Class: blue
1/1 [==============================] - 0s 405ms/step
[[3.517230